### ISSUE TITLE
Named functions are broken

### ISSUE THREAD

**Issue by AMiller42** [Lyxal/Vyxal#41] opened 2021-05-02 16:42 UTC
Not sure what happened, since named functions used to work, but they aren’t now.

Example: [Try it Online!](http://lyxal.pythonanywhere.com?flags=&code=%40func%3A1%7C%C2%BD%3B%0A10%20%40func%3B&inputs=&header=&footer=)

**Comment by ysthakur** [comment] 2021-05-02 18:14
May be a regression caused by [this](https://chat.stackexchange.com/transcript/message/57851812#57851812) change

**Comment by Lyxal** [comment] 2021-05-02 22:45
This is fixed in a recent commit

**Closed** 2021-05-02 22:45 UTC
